<header>
    <div class="header-container">
        <a href="index.php">
            <img class="about-logo-image" alt="GamesRUs Logo" src="images/logo.png">
        </a>
        <div class="nav-container">
            <select id="nav-select">
                <option value="">Select an option...</option>
                <option value="index.php">Home</option>
                <option value="gallery.php">Gallery</option>
                <option value="games.php">Games</option>
                <option value="add.php">Add</option>
            </select>
        </div>
        <div class="search-container">
            <input type="text" placeholder="Search...">
        </div>
    </div>
</header>
